### ISSUE TITLE
How to use the branch for training using gluon cv??

### ISSUE THREAD

**Issue by Ram124** [ijkguo/mx-rcnn#106]
@ijkguo 
Hi, Can You provide me some steps for working on gluon cv in dev branch?
I am getting very bad results in master branch. Training script (train.py) is wrong i guess in Master branch..
Test.py working fine if i use it with the other trained model which was trained using previous commit in apache mxnet repo.. Now  that repo has also changed... Could you please help me out in this.. 

Thank You

**Comment by ijkguo** [comment]
It is not wrong.

**Comment by ijkguo** [comment]
I finally understand what you mean.

The master branch is consistent with apache/mxnet. The rcnn example in apache/mxnet was the same with release v5.1 and now the same with release v6. v5.1 is fast but super complex. v6 is simple but slower because it is all numpy. I can reproduce the released models with both v5.1 and v6.

In dev branch, files starting with `sym` uses symbolic interface while files starting with `gluon` or `nd` uses imperative/gluon interface. To use `nd` or `gluon`, `gluoncv` is required as additional dependency.

From your description, you have a model trained with v5.1 on your own dataset. If you do not wish to check how https://github.com/ijkguo/mx-rcnn/issues/105 happened, you can continue using v5.1.

**Comment by ijkguo** [comment]
Moved to https://github.com/ijkguo/mx-rcnn/issues/105
